language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend

  - docker tag udagram-reverseproxy bambuvn/udagram-reverseproxy-seconds:v4a
  - docker tag udagram-api-feed bambuvn/udagram-api-feed-seconds:v4a
  - docker tag udagram-api-user bambuvn/udagram-api-user-seconds:v4a
  - docker tag udagram-frontend bambuvn/udagram-frontend-seconds:local

# Build and Push
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push bambuvn/udagram-reverseproxy-seconds:v4a
  - docker push bambuvn/udagram-api-feed-seconds:v4a
  - docker push bambuvn/udagram-api-user-seconds:v4a
  - docker push bambuvn/udagram-frontend-seconds:local
